// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbrBokiG5SRpux-sApdIn0YlXVMscMC1w',
    appId: '1:691187048995:web:7c0ea5078461ec509d8796',
    messagingSenderId: '691187048995',
    projectId: 'portafolio-e67f0',
    authDomain: 'portafolio-e67f0.firebaseapp.com',
    databaseURL: 'https://portafolio-e67f0-default-rtdb.firebaseio.com',
    storageBucket: 'portafolio-e67f0.firebasestorage.app',
    measurementId: 'G-8T8GJYCRP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPiX8HNbh1IV5WHNlbeqtSsUPFkzlrCk8',
    appId: '1:691187048995:android:60343dad5ca618289d8796',
    messagingSenderId: '691187048995',
    projectId: 'portafolio-e67f0',
    databaseURL: 'https://portafolio-e67f0-default-rtdb.firebaseio.com',
    storageBucket: 'portafolio-e67f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhEdMHnHPD8vXBfLtVOW4jtoMhSIw-CKw',
    appId: '1:691187048995:ios:8a88634cd4b07bef9d8796',
    messagingSenderId: '691187048995',
    projectId: 'portafolio-e67f0',
    databaseURL: 'https://portafolio-e67f0-default-rtdb.firebaseio.com',
    storageBucket: 'portafolio-e67f0.firebasestorage.app',
    iosBundleId: 'com.sebas.bejar.portafolioProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhEdMHnHPD8vXBfLtVOW4jtoMhSIw-CKw',
    appId: '1:691187048995:ios:8a88634cd4b07bef9d8796',
    messagingSenderId: '691187048995',
    projectId: 'portafolio-e67f0',
    databaseURL: 'https://portafolio-e67f0-default-rtdb.firebaseio.com',
    storageBucket: 'portafolio-e67f0.firebasestorage.app',
    iosBundleId: 'com.sebas.bejar.portafolioProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbrBokiG5SRpux-sApdIn0YlXVMscMC1w',
    appId: '1:691187048995:web:1fdb60e411844c709d8796',
    messagingSenderId: '691187048995',
    projectId: 'portafolio-e67f0',
    authDomain: 'portafolio-e67f0.firebaseapp.com',
    databaseURL: 'https://portafolio-e67f0-default-rtdb.firebaseio.com',
    storageBucket: 'portafolio-e67f0.firebasestorage.app',
    measurementId: 'G-7YPVMZ8T8C',
  );
}
